version: '3'
services:
  webserver:
    build: .
    ports:
      - "51127:80"
    volumes:
      - ./:/var/www/html
      - ../MedicalAIDiseaseDiagnostic/:/var/www/html/finalp
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
